swagger: '2.0'
info:
  title: Notifications webhook receiver
  description: API Specification to be able to receive notifications from the NRC
  contact:
    url: https://github.com/VNG-Realisatie/gemma-zaken
  version: v1
basePath: /
consumes:
  - application/json
produces:
  - application/json
securityDefinitions: {}
security: []
paths: {}
definitions: {}
